# Generated by Django 6.0.2 on 2026-02-06 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('raw_video', models.FileField(upload_to='raw/')),
                ('style_hint', models.CharField(default='modern, cinematic, vibrant', help_text='Style hint for AI visual generation', max_length=255)),
                ('use_api_transcription', models.BooleanField(default=True, help_text='Use OpenAI API for transcription (vs local Whisper)')),
                ('skip_image_generation', models.BooleanField(default=False, help_text='Skip AI image generation (use placeholder visuals)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('mapping', 'Mapping Visuals'), ('generating', 'Generating Images'), ('rendering', 'Rendering Video'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_message', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('transcript_data', models.JSONField(blank=True, null=True)),
                ('visual_prompts_data', models.JSONField(blank=True, null=True)),
                ('visuals_data', models.JSONField(blank=True, null=True)),
                ('output_video', models.FileField(blank=True, null=True, upload_to='output/')),
                ('props_file', models.FileField(blank=True, null=True, upload_to='props/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Video Project',
                'verbose_name_plural': 'Video Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisualAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(help_text='Start time in seconds')),
                ('image', models.ImageField(upload_to='assets/')),
                ('prompt', models.TextField(blank=True, help_text='AI prompt used to generate this image')),
                ('is_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_assets', to='video.videoproject')),
            ],
            options={
                'verbose_name': 'Visual Asset',
                'verbose_name_plural': 'Visual Assets',
                'ordering': ['start_time'],
            },
        ),
    ]
