# Generated by Django 6.0.2 on 2026-02-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoproject',
            name='use_api_transcription',
        ),
        migrations.AddField(
            model_name='videoproject',
            name='image_provider',
            field=models.CharField(choices=[('dalle3', 'DALL-E 3'), ('imagen', 'Imagen 3'), ('gemini_flash', 'Gemini Flash')], default='dalle3', help_text='Provider for image generation', max_length=20),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='llm_provider',
            field=models.CharField(choices=[('openai_gpt4', 'GPT-4o'), ('openai_gpt4_mini', 'GPT-4o Mini'), ('gemini_pro', 'Gemini Pro'), ('gemini_flash', 'Gemini Flash')], default='openai_gpt4', help_text='Provider for visual prompt generation', max_length=20),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='transcription_provider',
            field=models.CharField(choices=[('openai_whisper', 'OpenAI Whisper'), ('gemini', 'Gemini Audio'), ('local_whisper', 'Local Whisper')], default='openai_whisper', help_text='Provider for audio transcription', max_length=20),
        ),
    ]
