# Generated by Django 6.0.2 on 2026-02-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_remove_videoproject_use_api_transcription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoproject',
            name='image_provider',
            field=models.CharField(choices=[('dalle3', 'DALL-E 3'), ('imagen', 'Imagen 3'), ('gemini_flash', 'Gemini Flash'), ('mock', 'Mock (Testing)')], default='dalle3', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='llm_provider',
            field=models.CharField(choices=[('openai_gpt4', 'GPT-4o'), ('openai_gpt4_mini', 'GPT-4o Mini'), ('gemini_pro', 'Gemini Pro'), ('gemini_flash', 'Gemini Flash'), ('mock', 'Mock (Testing)')], default='openai_gpt4', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='skip_image_generation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='style_hint',
            field=models.CharField(default='modern, cinematic, vibrant', max_length=255),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='transcription_provider',
            field=models.CharField(choices=[('openai_whisper', 'OpenAI Whisper'), ('gemini', 'Gemini Audio'), ('local_whisper', 'Local Whisper'), ('mock', 'Mock (Testing)')], default='openai_whisper', max_length=20),
        ),
        migrations.AlterField(
            model_name='visualasset',
            name='prompt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='visualasset',
            name='start_time',
            field=models.FloatField(),
        ),
    ]
