# Generated by Django 5.2.11 on 2026-02-06 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_videoproject_image_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/')),
                ('config', models.JSONField(default=dict, help_text='Configuration for colors, fonts, layout preferences, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='videoproject',
            name='global_style',
            field=models.CharField(default='modern', help_text='e.g. 3D Tactile, Flat Minimalist, Cyberpunk', max_length=100),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='processed_video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='optimized/'),
        ),
        migrations.AddField(
            model_name='videoproject',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('analyzing', 'Analyzing'), ('ready', 'Ready to Edit'), ('rendering', 'Rendering Video'), ('completed', 'Completed'), ('failed', 'Failed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='videoproject',
            name='style_hint',
            field=models.CharField(default='modern', max_length=255),
        ),
        migrations.CreateModel(
            name='VideoSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('start_time', models.FloatField()),
                ('end_time', models.FloatField()),
                ('transcript', models.TextField(blank=True)),
                ('asset_type', models.CharField(choices=[('ai_image', 'AI Generated Image'), ('user_upload', 'User Uploaded Asset'), ('video_clip', 'Video Clip'), ('meme', 'Meme'), ('emoji', 'Emoji')], default='ai_image', max_length=20)),
                ('asset_file', models.FileField(blank=True, null=True, upload_to='assets/')),
                ('layout_event', models.CharField(choices=[('split', 'Standard Split (50/50)'), ('bottom_full', 'Focus Bottom (Fullscreen)'), ('top_full', 'Focus Top (Fullscreen)')], default='split', max_length=20)),
                ('animation_type', models.CharField(choices=[('ken_burns', 'Ken Burns (Slow Zoom)'), ('side_slide', 'Side Slide'), ('static', 'Static')], default='ken_burns', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='video.videoproject')),
            ],
            options={
                'verbose_name': 'Video Segment',
                'verbose_name_plural': 'Video Segments',
                'ordering': ['order', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='videoproject',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='video.videotemplate'),
        ),
    ]
